//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package org.evenos.zerlina.activities;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import org.evenos.zerlina.activities.PasswordActivity;
import com.itkamer.xonta.R.id;

public final class PasswordActivity_
    extends PasswordActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        Resources resources_ = this.getResources();
        password_no_match = resources_.getString(com.itkamer.xonta.R.string.password_no_match);
        password_wrong = resources_.getString(com.itkamer.xonta.R.string.password_wrong);
        checking_password = resources_.getString(com.itkamer.xonta.R.string.checking_password);
        loading_data = resources_.getString(com.itkamer.xonta.R.string.loading_data);
        encrypting_data = resources_.getString(com.itkamer.xonta.R.string.encrypting_data);
        no_password_entered = resources_.getString(com.itkamer.xonta.R.string.no_password_entered);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PasswordActivity_.IntentBuilder_ intent(Context context) {
        return new PasswordActivity_.IntentBuilder_(context);
    }

    public static PasswordActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new PasswordActivity_.IntentBuilder_(fragment);
    }

    public static PasswordActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new PasswordActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        password = ((EditText) hasViews.findViewById(id.enter_password_textfield));
        enterPassword = ((Button) hasViews.findViewById(id.enter_password_button));
        {
            View view = hasViews.findViewById(id.enter_password_button);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PasswordActivity_.this.enterPassword();
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) hasViews.findViewById(id.chose_password_textfield_1));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                        PasswordActivity_.this.onTextChanges(view);
                    }

                    @Override
                    public void afterTextChanged(Editable s) {
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void enableEnterPasswordButton() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                PasswordActivity_.super.enableEnterPasswordButton();
            }

        }
        );
    }

    @Override
    public void disableEnterPasswordButton() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                PasswordActivity_.super.disableEnterPasswordButton();
            }

        }
        );
    }

    @Override
    public void showWrongPasswordToast() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                PasswordActivity_.super.showWrongPasswordToast();
            }

        }
        );
    }

    @Override
    public void dismissProgressDialog() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                PasswordActivity_.super.dismissProgressDialog();
            }

        }
        );
    }

    @Override
    public void startMainActivity(final String key) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                PasswordActivity_.super.startMainActivity(key);
            }

        }
        );
    }

    @Override
    public void showPasswordActivity() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                PasswordActivity_.super.showPasswordActivity();
            }

        }
        );
    }

    @Override
    public void setPasswordAndLogIn(final String string) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    PasswordActivity_.super.setPasswordAndLogIn(string);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void validatePassword() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    PasswordActivity_.super.validatePassword();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PasswordActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PasswordActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PasswordActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PasswordActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
